service: e-diary-api
runtime: custom
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: "tactile-sentry-341817:europe-west1-b:e-diary-api=tcp:5432"